FROM openjdk:17-jdk-alpine3.14
WORKDIR /backend
EXPOSE 8080
COPY target/ecommerce-0.0.1-SNAPSHOT.jar /backend/ecommerce.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
#"-Dspring.profiles.active=docker",

